image:
  repository: keelhq/keel
  tag: 0.17.0-rc1
  pullPolicy: Always

# Enable insecure registries
insecureRegistry: false

# Polling is enabled by default,
# you can disable it setting value below to false
polling:
  enabled: true

# Helm provider support
helmProvider:
  version: "v3"
  enabled: true

basicauth:
  enabled: true
  user: "admin"
  password: "password"

service:
  enabled: true
  type: NodePort
  externalPort: 9300
  clusterIP: ""
