{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "keel.name" . }}
rules:
{{- range .Values.rbac.clusterRole.rules }}
- apiGroups: {{ .apiGroups | toYaml | nindent 4 }}
  resources: {{ .resources | toYaml | nindent 4 }}
  verbs: {{ .verbs | toYaml | nindent 4 }}
{{- end }}
{{ end }}
