{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "keel.name" . }}
rules:
{{- range .Values.rbac.clusterRole.rules }}
  - apiGroups: {{ .apiGroups | toYaml | nindent 6 }}
    resources: {{ .resources | toYaml | nindent 6 }}
    verbs: {{ .verbs | toYaml | nindent 6 }}
{{- end }}
{{ end }}
