apiVersion: v1
name: keel
description: Open source, tool for automating Kubernetes deployment updates. Keel is stateless, robust and lightweight.
version: 0.9.11
# Note that we use appVersion to get images tag, so make sure this is correct.
appVersion: 0.16.1
keywords:
- kubernetes deployment
- helm release
- continuous deployment
home: https://keel.sh
sources:
- https://github.com/keel-hq/keel
maintainers:
- name: rimusz
  email: rmocius@gmail.com
- name: rusenask
  email: karolis.rusenas@gmail.com
engine: gotpl
icon: https://raw.githubusercontent.com/keel-hq/keel/master/static/keel-logo.png
